"-----------------------------------------------------------------------
" File:     vimrc - a configuration file for the vim text editor
" By:       John Magolske @ http://b79.net/contact
" License:  GPL v3
" Notes:    includes bits & tips from numerous sources ...
"-----------------------------------------------------------------------


" ---- General Settings ------------------------------------------------

" Use Vim rather then Vi settings (must be first; changes other options)
set nocompatible

set runtimepath=~/.vim,$VIMRUNTIME

"let &termencoding = &encoding
"set encoding=utf-8

set writebackup     " backup before overwriting a file, remove after write
set nobackup		" don't accumulate backup file
"set backupcopy=yes       " make a copy of the file and overwrite the original one
"set backupdir=~/.vimback " place backup files in the ~/.vimback directory

" Enable use of mouse in terminals
set mouse=a
set mousemodel=popup_setpos

" generate CSS XHTML when using the :TOhtml command
let html_use_css = 1
let use_xhtml = 1

set history=300	   " keep 300 lines of command line history

" use backquote key for the leader, hit twice to type backquote character
let mapleader = "`"
imap <leader>` <esc>:set paste<CR>a`<esc>:set nopaste<CR>a
let maplocalleader = "`"


" ---- Appearance ------------------------------------------------------

" turn off visual & audio bell
set vb t_vb=

" leave a one character wide foldcolumn on the left side of the window
set fdc=1

" when wrapping long lines, do not break words
set lbr

" display as much as possible of the last line (minimize @'s)
set display=lastline

" min # of screen columns to keep left and right of the cursor when nowrap is set
set sidescrolloff=1
" min # of columns to scroll horizontally when the cursor moves off the screen
set sidescroll=1

"set helpheight=999      " full-screen help window

" set color scheme
colo jfm

" Switch syntax highlighting on when the terminal has colors.
" Also switch on highlighting the last used search pattern.
if &t_Co > 2 || has("gui_running")
  syntax on
  set hlsearch
endif

" so the title of file being edited shows up in title-bar
set title

" text-cursor color by mode in xterm, linux console and screen.linux console:
" normal mode = golden, insert mode = green, return to green when leaving vim
if &term =~ "xterm"
    :silent !echo -ne "\033]12;GoldenRod\007"
    set t_SI+=]12;green
    set t_EI+=]12;GoldenRod
    autocmd VimLeave * :!echo -ne "\033]12;green\007"
    " show 'Vim, filename' in xterm title bar
    set titlestring=\%(\%M%)%t\ (Vim)
    " Set xterm to 16 colors (don't I want more?)
    set t_Co=16
endif
if &term == "linux" && !has("gui_running")
    set t_ve+=[?17;183;95c  " yellow
    au InsertEnter * set t_ve+=[?17;207;111c  " green
    au InsertLeave * set t_ve+=[?17;183;95c  " yellow
    autocmd VimLeave * set t_ve+=[?17;207;111c  " green
endif
if &term == "screen.linux"
  set t_ve+=[34l
  au InsertEnter * set t_ve+=[34h[?25h    " cnorm
  au InsertLeave * set t_ve+=[34l           " cvvis
  autocmd VimLeave * set t_ve+=[34h[?25h
  " show 'V:filename' as window name for screen (Tip 1126)
  set titlestring=\%(\%M%)V:%t
  set t_ts=k
  set t_fs=\
endif

if &term == "linux" || &term == "screen.linux"
    " set Del & BackSpace keys to function properly (is this neccessary?)
    set t_kb=
    set t_kD=[3~
    " use the blink attribute for bright background (console_codes(4)) & the
    " bold attribute for bright foreground. The redefinition of t_AF is
    " necessary for bright \"Normal" highlighting to not influence the rest.
    " http://vim.wikia.com/wiki/Get_bright_background_colors_in_Linux_console
    if has("terminfo")
        set t_Co=16
        set t_AB=[%?%p1%{7}%>%t5%p1%{8}%-%e25%p1%;m[4%dm
        set t_AF=[%?%p1%{7}%>%t1%p1%{8}%-%e22%p1%;m[3%dm
    endif
endif

set cmdheight=1    " command line is one screen line tall
set laststatus=2   " status bar is always visible

" Status line settings
set stl=%<\ %F%{GitBranch()}%(\ %h%)\ %2*%M%*%(\ (%R)\ %)\ %1*│%*%{len(filter(range(1,bufnr('$')),'buflisted(v:val)'))}\ %=\ %1*<%*%B%1*>%*\ %c,%l\ %3*\ %p%%\ %*

set shortmess=aO

"hi User1 term=inverse,bold cterm=inverse,bold ctermfg=red

set showcmd  " display incomplete commands


" ---- Movement, Behaviour of Text -------------------------------------

" Expand tabs to 4 spaces, BackSpace treats 4 spaces like 1 tab (Tip#12)
set et
set tabstop=4
set softtabstop=4

" (auto)indent 4 spaces with > , >> , cindent , etc.
set shiftwidth=4

" allow backspacing over autoindent, line breaks, start of insert
" while in insert mode
set backspace=indent,eol,start

" allow cursor to move to the previous/next line
set ww=b,s,h,l,>,<,[,],~

set ignorecase     " super handy in combo with smartcase!
set smartcase      " override 'ignorecase' for search pattern w/ upper case chars
set incsearch      " do incremental searching

" enable tab command completion with wildmenu (Tip #1045)
set wildmenu
set wildignore=*.dll,*.o,*.pyc,*.bak,*.exe,*.jpg,*.jpeg,*.png,*.gif
set wildmode=list:longest,full
set wcm=<C-Z>

" do not load matchparen plugin, no auto-highlighting of matching parens
let loaded_matchparen = 1

" closetag -- set unaryTagsStack to its default value for html
" Requires: closetag.vim (script)
let b:closetag_html_style=1
" auto source closetag plugin for given filetypes
au Filetype html,xml,xsl source ~/.vim/plugin/closetag.vim

" automatically insert current comment leader after <Enter> in Insert mode
set fo=r

" always set autoindenting on
set ai

" disable auto-indenting for html and xml files
autocmd BufEnter *.html setlocal indentexpr=
autocmd BufEnter *.htm setlocal indentexpr=
autocmd BufEnter *.xml setlocal indentexpr=
autocmd BufEnter *.xsd setlocal indentexpr=

if version >= 600
  filetype plugin indent on
endif

" When selecting text in Visual block mode, allow cursor to be positioned 
" beyond the ends of lines where there are no actual characters.
set virtualedit=block

set timeout
"set ttimeout
"set notimeout
set timeoutlen=1300
set ttimeoutlen=100

" deactivate scrollbind whenever entering one window, re-activate it when
" entering the other -- drchip via vim_use
fun! Scd()
 augroup SCBNOSCB
   au!
   au WinEnter * if winnr() == 1|set scb|endif
   au WinEnter * if winnr() == 2|set scb|endif
   au WinLeave * if winnr() == 1|set noscb|endif
  augroup END
  norm! zR
  wincmd l
  norm! zR
  wincmd h
endfun
command Scd :call Scd()


" ---- Buffer & File Navigation ----------------------------------------

" switch between buffers without each one having to be saved first
set hidden 

" automatically change current directory when switching buffers
au BufEnter,BufFilePost * if expand("<afile>") !~ "://" | lcd %:p:h | endif

" go to next buffer / previous buffer
map <F2> :bn<CR>
imap <F2> <esc>:bn<CR>a
map <F1> :bp<CR>
imap <F1> <esc>:bp<CR>a

" toggle between two files/buffers. Precede this mapping with a number to go to
" a given buffer number. Messes up marks wrt the ` char ... may reconsider ...
map <leader>` <c-^>
map <leader><BackSpace> <c-^>
imap <leader><BackSpace> <esc><c-^>a
" go straight to a buffer by number:
map <leader>1 :b1<cr>
map <leader>2 :b2<cr>
map <leader>3 :b3<cr>
map <leader>4 :b4<cr>
map <leader>5 :b5<cr>
map <leader>6 :b6<cr>
map <leader>7 :b7<cr>
map <leader>8 :b8<cr>
map <leader>9 :b9<cr>
map <leader>0 :b10<cr>

" buftabs - shows list of buffers in the in the command-line area
" Requires: buftabs.vim (script)
" List buffers & prompt for a selection, exits leaving buftabs displayed
map <leader><CR> :echo Buftabs_show()<CR>:buffers<CR>:buffer 
"map <leader><CR> :buffers<CR>:buffer<Space> <C-Z><C-Z>
map! <leader><CR> <esc>:buffers<CR>:buffer 
let g:buftabs_only_basename=1

" Browse buffers with bufferlist
" Requires: bufferlist.vim (script)
map! <leader>b <esc>:echo Buftabs_show()<CR>:call BufferList()<CR>
map <leader>b :echo Buftabs_show()<CR>:call BufferList()<CR>
let g:BufferListWidth = 28
let g:BufferListMaxWidth = 65
hi BufferSelected term=NONE ctermfg=grey ctermbg=darkgrey cterm=bold
hi BufferNormal term=NONE ctermfg=darkyellow ctermbg=black cterm=NONE

" Browse buffers with the bufexplorer plugin
" Requires: bufexplorer.vim (script)
map <leader>B :VSBufExplorer<CR>
map! <leader>B :VSBufExplorer<CR>

" delete buffer without closing window
"nmap <leader>b- :bnext<CR>:bdelete#<CR>:echo Buftabs_show()<CR>

" VtreeExplorer (file explorer) settings
" Requires: VtreeExplorer.vim (script)
let treeExplNoList = 1      " don't list VtreeExplorer in buffer list
let treeExplDirSort = 1     " sort directories first
let treeExplVertical = 1    " split vertically
let treeExplWinSize = 32    " make vertical split 32 columns wide
let treeExplCloseExp = 1    " close VtreeExplorer after use
"open VtreeExplorer
"map <leader>f :echo Buftabs_show()<CR>:VSTreeExplore<CR>
map <silent> <leader>f :VSTreeExplore<CR>
map! <leader>f <esc>:VSTreeExplore<CR>
" open VtreeExplorer & leave the explorer open
map <silent> <leader>F :let treeExplCloseExp=0<CR>:VSTreeExplore<CR>
map! <leader>F <esc>:VSTreeExplore<CR>
command Vt :VTreeExplore

" settings for the MRU (Most Recently Used files) plugin
" Requires: mru.vim (script)
"let MRU_File = '~/.vim/vim_mru_files' (<-- why won't this set?)
command Mr :MRU
let MRU_Max_Entries = 700
let MRU_Window_Height = 15


" ---- Abbreviations ---------------------------------------------------

" year/month/date/day/time/zone abbreviation
" Linux
iab ydt <c-r>=strftime("%Y/%m/%d\ %a\ %k:%M\ %Z")<cr>
" mswin
"iab ydt <c-r>=strftime("%Y/%m/%d\ %a\ %I:%M\ %z")<cr>

" stamp a document retrieved from the net with date & time accessed
iab acc [accessed <c-r>=strftime("%Y/%m/%d\ %a\ %k:%M\ %Z")<cr>]

iab <l <lt>leader>
ia +/- ±


" ---- Insert Completion ----------------------------------------------

" initiate Omni completion while typing a word (h: compl-omni)
imap <leader>\ 

" set natural language completion dictionary
set dictionary+=/usr/share/dict/american-english-large

" Completion options
set completeopt+=menuone        " always show the completion menu
set completeopt+=preview        " sometimes annoying window on the top
set completeopt+=longest        " do not select the first variant by default

" SuperTab settings
" Requires: supertab.vim (script)
" Set default tab completion key to be <leader><space> and allow the ability
" to toggle between that sequence and simply using the <tab> key:
let SuperTabMappingForward = '<leader><space>'
let g:SuperTab_tab = 0
function! ToggleSuperTabMap()
    if g:SuperTab_tab == 1
        let g:SuperTabMappingForward = "<leader><space>"
        let g:SuperTabMappingTabLiteral = "<tab>"
        so ~/.vim/plugin/supertab.vim
        let g:SuperTab_tab = 0
        echo "SuperTab key = <leader><space>"
    else
        let g:SuperTabMappingForward = "<tab>"
        let g:SuperTabMappingTabLiteral = "<leader><space>"
        so ~/.vim/plugin/supertab.vim
        let g:SuperTab_tab = 1
        echo "SuperTab key = <tab>"
    endif
endfunction
map <leader><tab> :call ToggleSuperTabMap()<CR>
imap <leader><tab> <esc>:call ToggleSuperTabMap()<CR>a

" default completion type
let g:SuperTabDefaultCompletionType = "<c-x><c-n>"

" completion type is saved for the duration of your vim session or until
" you enter a different completion mode.
let g:SuperTabRetainCompletionDuration = "session"

" Alternate completion modes:
" n=file, k=dictionary, l=whole-lines, ]=tags f=file-names o=omni
imap <leader>xn <c-x><c-n>
imap <leader>xk <c-x><c-k>
imap <leader>xl <c-x><c-l>
imap <leader>x] <c-x><c-]>
imap <leader>xf <c-x><c-f>
imap <leader>xo <c-x><c-o>
map <leader>xh :SuperTabHelp<CR>
imap <leader>xh <esc>:SuperTabHelp<CR>a

let g:SuperTab_tab = 0
function! ToggleSuperTabMap()
    let g:SuperTabMappingForward = g:SuperTab_tab ? '<tab>' : '<leader><space>'
    let g:SuperTab_tab = !g:SuperTab_tab
    exec 'imap ' . g:SuperTabMappingForward . ' <c-n>'
endfunction
map <silent> <F3> :call ToggleSuperTabMap()<CR>

" use syntax highlighting defs to enable Omni-Completion after any
" :filetype command using best available method
" http://vim.runpaint.org/typing/auto-completing-text/
if has("autocmd") && exists("+omnifunc")
  autocmd Filetype *
    \   if &omnifunc == "" |
    \     setlocal omnifunc=syntaxcomplete#Complete |
    \   endif
endif


" -------- Dictionaries ------------------------------------------------

" filter word under cursor through dict, view definition(s)
map <leader>di be:!def <cWORD><CR>
" filter word before cursor through dict, read definition(s) into file
imap <leader>di <Esc>b:r !def <cWORD><CR>a

" filter word under cursor, view definition(s) [english to spanish]
map <leader>de be:!sdef -e <cWORD><CR>
" filter word before cursor, read definition(s) into file
imap <leader>de <Esc>b:r !sdef -e <cWORD><CR>a
" filter word under cursor, view definition(s) [spanish to english]
map <leader>ds be:!sdef -s <cWORD><CR>
" filter word before cursor, read definition(s) into file
imap <leader>ds <Esc>b:r !sdef -s <cWORD><CR>a

" filter word under cursor through the i2e dictionary [english to spanish]
map <leader>de2 be:!i2e-cli -e <cWORD><CR>
map <leader>dE2 be:!i2e-cli <cWORD><CR>
" filter word before cursor through i2e, read definition(s) into file
imap <leader>de2 <Esc>b:r !i2e-cli -e <cWORD><CR>a
imap <leader>dE2 <Esc>b:r !i2e-cli <cWORD><CR>a
" filter word under cursor through the i2e dictionary [spanish to english]
map <leader>ds2 be:!i2e-cli -re <cWORD><CR>
map <leader>dS2 be:!i2e-cli -r <cWORD><CR>
" filter word before cursor through i2e, read definition(s) into file
imap <leader>ds2 <Esc>b:r !i2e-cli -re <cWORD><CR>a
imap <leader>dS2 <Esc>b:r !i2e-cli -r <cWORD><CR>a

" filter word under cursor through the 'words' latin/english dictionary
" using the wrapper script 'latin'.   English/Latin:
map <leader>del be:!latin -e <cWORD><CR>
imap <leader>del <Esc>b:r !latin -e <cWORD><CR>a
" Latin/English:
map <leader>dle be:!latin <cWORD><CR>
imap <leader>dle <Esc>b:r !latin <cWORD><CR>a

" Toggle English spell checking on/off
let g:SpellEng = 0
function! ToggleSpellEng()
    if g:SpellEng == 0
        setlocal spell spelllang=en_us
        let g:SpellEng = 1
        let g:SpellEsp = 0
        echo "Spell checking: English"
    else
        setlocal nospell
        let g:SpellEng = 0
        echo "Spellchecking Off"
    endif
endfunction
map <F5> :call ToggleSpellEng()<CR>
imap <F5> <esc>:call ToggleSpellEng()<CR>a

" Toggle Español spell checking on/off
let g:SpellEsp = 0
function! ToggleSpellEsp()
    if g:SpellEsp == 0
        setlocal spell spelllang=es
        let g:SpellEsp = 1
        let g:SpellEng = 0
        echo "Spell checking: Español"
    else
        setlocal nospell
        let g:SpellEsp = 0
        echo "Spellchecking Off"
    endif
endfunction
map <F6> :call ToggleSpellEsp()<CR>
imap <F6> <esc>:call ToggleSpellEsp()<CR>a


" ---- Reformatting Paragraphs, etc ------------------------------------

" filter through par, a paragraph reformatter 
" Requires: par - http://www.nicemice.net/par/
" Set something like this in zshrc:
"     export PARINIT="B=.,?_A_a_0_q_Q Q=_s>|"
" Note the _Q in there, see par(1) -- it cooresponds to a double quote. Remove
" it if reformatting Vim comments, but leave it in otherwise so regular quotes
" in prose, etc won't get messed up. Re par not handling unicode, see tip584,
" or http://vim.wikia.com/wiki/Awesome_text_formatter
" reformat paragraph; break at default 80 columns, leave first line of paragraph
" flush left (for bullet or numbered list) but indent all other lines 2 spaces:
noremap <leader>q2 {v}!par -w s0rT4p2dh1 <CR>}lz.
noremap! <leader>q2 <esc>{v}!par -w s0rT4p2dh1<CR>}lz.i
vmap <leader>q2 !par -w s0rT4p2dh1<CR>}
" ... 3 spaces:
noremap <leader>q3 {v}!par -w s0rT4p3dh1<CR>}lz.
noremap! <leader>q3 <esc>{v}!par -w s0rT4p3dh1<CR>}lz.i
vmap <leader>q3 !par -w s0rT4p3dh1<CR>}
" ... 4 spaces:
noremap <leader>q4 {v}!par -w s0rT4p4dh1<CR>}lz.
noremap! <leader>q4 <esc>{v}!par -w s0rT4p4dh1<CR>}lz.i
vmap <leader>q4 !par -w s0rT4p4dh1<CR>}
" ... 5 spaces:
noremap <leader>q5 {v}!par -w s0rT4p5dh1<CR>}lz.
noremap! <leader>q5 <esc>{v}!par -w s0rT4p5dh1<CR>}lz.i
vmap <leader>q5 !par -w s0rT4p5dh1<CR>}
" reformat paragraph; break at default 80 columns -- keep text centered
" vertically on the screen
"noremap <leader>ww {v}!par -w s0rT4<CR>}lz.
"noremap! <leader>ww <esc>{v}!par -w s0rT4<CR>}lz.i
"vmap <leader>ww !par -w s0rT4<CR>}
" 
" reformat paragraph; break at default 80 columns
noremap <leader>q8 {v}!par -w s0rT4<CR>}l
noremap! <leader>q8 <esc>{v}!par -w s0rT4<CR>}li
vmap <leader>q8 !par -w s0rT4<CR>}
" reformat paragraph; break at 70 columns
noremap <leader>qq {v}!par -w70 s0rT4<CR>}l
noremap! <leader>qq <esc>{v}!par -w70 s0rT4<CR>}li
vmap <leader>qq !par -w70 s0rT4<CR>}
" 
" reformat paragraph; break at 74 columns
noremap <leader>qw {v}!par -w74 s0rT4<CR>}l
noremap! <leader>qw <esc>{v}!par -w74 s0rT4<CR>}li
vmap <leader>qw !par -w74 s0rT4<CR>}
" 
" reformat paragraph; break at 60 columns
noremap <leader>q6 {v}!par -w62 s0rT4<CR>}l
noremap! <leader>q6 <esc>{v}!par -w62 s0rT4<CR>}li
vmap <leader>q6 !par -w62 s0rT4<CR>}
" 
" filter entire file through par; default = 80 columns
nmap <leader>qgg :% !par -w s0rT4<CR>
imap <leader>qgg <esc>:% !par -w s0rT4<CR>
" filter entire file through par; break at 70 columns
nmap <leader>qg7 :% !par -w70 s0rT4<CR>
imap <leader>qg7 <esc>:% !par -w70 s0rT4<CR>
" filter entire file through par; break at 62 columns
nmap <leader>qg6 :% !par -w62 s0rT4<CR>
imap <leader>qg6 <esc>:% !par -w62 s0rT4<CR>
" 
" filter through par, you supply the arguments (<leader>q<space>)
nmap <leader>q  {!}par 
imap <leader>q  <Esc>{!}par 
vmap <leader>q  !par 

" set lines to be broken after 80, 70, 60 columns, or to be not broken (=0)
command T8 :set textwidth=80
command T7 :set textwidth=70
command T6 :set textwidth=60
command T0 :set textwidth=0


" ---- Mappings --------------------------------------------------------

" clear search highlighting by hitting 'Return' key
nnoremap <CR> :nohlsearch<CR>/<BS><BS>

" go to command prompt using ; instead of : (avoiding the shift key...)
noremap ; :

" Use Space & BackSpace keys to scroll window forward & backward one screen
" while in normal mode
noremap <space> 
noremap <BackSpace> 

" in insert mode: yank word, line; delete word, line; put; undo; redo; put
imap <leader>yw <c-o>yw
imap <leader>yy <c-o>yy
imap <leader>dw <c-o>dw
imap <leader>dd <c-o>dd
imap <leader>u <c-o>u
imap <leader><c-r> <c-o>
imap <leader>p <c-o>p
" paste into gvim from other applications
imap <leader>P <c-o>"+gP

" paste/insert GNU Screen buffer, change default mappings
" Requires: screenpaste.vim (script), GNU Screen (external program)
map  <Leader>sp  <Plug>ScreenpastePut
map! <Leader>sp  <Plug>ScreenpastePut
map  <Leader>sgp <Plug>ScreenpasteGPut
nmap <Leader>sP  <Plug>ScreenpastePutBefore
nmap <Leader>sgP <Plug>ScreenpasteGPutBefore

" Go into -- (insert) VISUAL -- mode from insert mode
imap <leader>v <c-o>v

" Go into -- (insert) VISUAL BLOCK -- mode from insert mode 
imap <leader><c-v> <c-o>v<c-v>
map <leader><c-v> v<c-v>

" close window without deleting buffer
nmap <leader>w- :close<CR>

" Zoom into and out of a window (ZoomWin plugin):
nmap <leader>z :ZoomWin<CR>

" Set (or unset) all open windows to scroll together
command Scroll :windo setlocal scrollbind
command Scrollno :windo setlocal noscrollbind

" go to previous window / next window (see :h Ctrl-w_w)
map <F4> <c-w>w
imap <F4> <esc><C-w>wa
map <F3> <c-w>W
imap <F3> <esc><c-w>Wa

" quickfix commands, jump fore & aft when using :helpgrep (:helpg )
map <c-n> :cnext<CR>
map <c-p> :cprevious<CR>

" View personal tip sheet with less, in another Screen tty
" Requires: custom .txt file, GNU Screen
map <leader>h :silent !screen -t 'John-Vim' less -cL ~/comp/soft/vim/vim_how.txt<CR>
imap <leader>h <esc>:silent !screen -t 'John-Vim' less -cL ~/comp/soft/vim/vim_how.txt<CR>a

" F8 update (save) file (update only writes when buffer has been modified)
map! <F8> <esc>:update<CR>a
map  <F8> <esc>:update<CR>
" Alt-s update file
set <F29>=s
map <F29> <a-s>
map! <F29> <a-s>
map! <a-s> <esc>:update<CR>a
map  <a-s> <esc>:update<CR>

" <F9> toggle paste mode on/off, useful when pasting text into terminal Vim
set pastetoggle=<F9>        " toggle 'paste' option
map <F9>        :set invpaste paste?<CR>
imap <F9>   <C-O>:set invpaste<CR><C-O>/<BS>

" <F10> toggles numbered lines on/off
nmap <F10> :set nu!<CR>
imap <F10> <c-o>:set nu!<CR>

" reload vimrc file without having to quit & re-start
map <leader>rc <esc>:source ~/.vimrc<CR>
map! <leader>rc <esc>:source ~/.vimrc<CR>a
"map <leader>rc <esc>:so C:\Program Files\Vim\_vimrc<CR> " (mswin)
"map! <leader>rc <esc>:so C:\Program Files\Vim\_vimrc<CR>a

" open a window containing all highlight group names, in their own color
command Hi so $VIMRUNTIME/syntax/hitest.vim

" get unicode info for byte under cursor, more detailed info than default g8
" Requires: unicode (external program) - cli unicode database query tool
map g8 :normal! vy<cr><cr>:!unicode \"<cr>

" Remove trailing whitespace at the ends of lines ( or maybe: %s/\s\+$//e )
command Rws %s/\s*$//

" remove spaces between quote markers (> >) in emails (is this wrong?)
command Rqs :%s/>\s\+>/>>/g

" remove m$ ^M line endings (tip#26)
"command Ms :%s/\r/\r/g
command Ms :%s/\r//g

" replace the DOS style CR/LF line endings
command Mm :%s///g

" convert hex ascii codes to printable characters, eg:
" Hello%20World.%20%20Good%2c%20bye. --> Hello World.  Good, bye.
"for the whole file:
command Hac :%s/%\(\x\x\)/\=nr2char('0x'.submatch(1))/g  
"for the visually selected text:
vmap hac :s/%\(\x\x\)/\=nr2char('0x'.submatch(1))/g

"Detect filetype
command Ftd :filetype detect

" Set filetype to txt
command Txt :set filetype=txt

" view NERDCommenter help
" Requires: nerdmmenter.vim (script)
command Nerd :help NERDCommenter

" use the txp script to print a letter-style output...
" Requires: txp - custom shell script, see http://b79.net
command Let !txp -f11 -l72 -F0 %
" ...or regular output
command Txp !txp %

" replace curly quotes with straight quotes
cmap <leader>" % s/[“”]/"/g<cr>
cmap <leader>' % s/[‘’]/'/g<cr>

" replace all EM (U+2014) and EN (U+2013) dashes in file with two dashes
cmap <leader>- % s/[–—―Ñ]/--/g<cr>
" replace EM and EN dashes in file with two dashes, a space on either side
cmap <leader>_ % s/[–—―Ñ]/ -- /g<cr>

" replace all ellipsises (U+2026) with three decimals
cmap <leader>. % s/[…É]/.../g<cr>

" replace bullet characters (U+2022) with *
cmap <leader>8 %s/[•·]/*/g<cr>

" replace box drawing characters with ascii characters - + |
cmap <leader>\ % s/[┘┐┼┌└]/+/g<cr>:%s/─/-/g<cr>:%s/│/\|/g<cr>

cmap <leader>+ % s/[┛┓┏┗]/+/g<cr>:%s/[━┯┷]/-/g<cr>:%s/[┃┠┨]/\|/g<cr>
" replace box drawings character "heavy horizontal" (U+2501) with =
cmap <leader>= %s/━/=/g<cr>

" replace control characters in html files (for curly quotes, etc.) with ascii
cmap <leader>,- % s/[]/--/g<cr>
cmap <leader>,_ % s/[]/ -- /g<cr>
cmap <leader>,' % s/[]/'/g<cr>
cmap <leader>," % s/[]/"/g<cr>
cmap <leader>,. % s//.../g<cr>

"these next two don't work...they quit & not continue if something isn't found
" replace all the above; curly quotes, EM & EN dashes, ellipses
"cmap <leader>a :%s/[“”]/"/g<cr> \|:%s/[‘’]/'/g<cr> \|:%s/[—–Ð]/--/g<cr> \|:%s/…/.../g<cr>
cmap <leader>A :%s/[“”]/"/g<cr>:%s/[‘’]/'/g<cr>:%s/[—–Ð]/ -- /g<cr>:%s/…/.../g<cr>
" replace Õ Ò Ó Ê ¥ with ascii punctuation (that 
cmap <leader>o :%s/[ÕÔ]/'/g<cr>:%s/[ÒÓ]/"/g<cr>:%s/¥/*/g<cr>:%s/Ê//g<cr>:%s/	//g<cr>
cmap <leader>Y %s/^¥¥*/*/g<cr>

" uppercase first letter of sentences in a file
command Cs %s/[.!?]\_s\+\a/\U&\E/g
" uppercase first letter of sentences in visually selected text
vmap cs :s/[.!?]\_s\+\a/\U&\E/g<CR>

" visually select text then press ~ to convert to UPPER CASE, then lower case,
" then Title Case... Keep pressing ~ until you get the case you want.
" http://vim.wikia.com/wiki/Switching_case_of_characters
function! TwiddleCase(str)
  if a:str ==# toupper(a:str)
    let result = tolower(a:str)
  elseif a:str ==# tolower(a:str)
    let result = substitute(a:str,'\(\<\w\+\>\)', '\u\1', 'g')
  else
    let result = toupper(a:str)
  endif
  return result
endfunction
vnoremap ~ ygv"=TwiddleCase(@")<CR>Pgv

" process with wcalc -- position cursor immediately (or some number of spaces)
" after the end of the formula in insert mode, <leader>= will output solution
" in scientific notation:
"inoremap <leader>= <Esc>Bi<CR><Esc>:co-<CR>j!!wcalc<CR>-$Jk$J$a<space>
" or with 1021 digits after the decimal point:
"inoremap <leader>+ <Esc>Bi<CR><Esc>:co-<CR>j!!wcalc -P1021<CR>-$Jk$J$a<space>

" filter through the 'boxes' program, surround blocks of text with a box of
" text, useful for adding commenting to blocks of code (find other mapping...)
"vmap <leader>x3 !boxes -d pound-cmt<CR>
"nmap <leader>x3 !!boxes -d pound-cmt<CR>
"vmap <leader>x# !boxes -d shell<CR>
"nmap <leader>x# !!boxes -d shell<CR>
"vmap <leader>x' !boxes -d vim-cmt<CR>
"nmap <leader>x' !!boxes -d vim-cmt<CR>
"vmap <leader>x" !boxes -d vim-shell<CR>
"nmap <leader>x" !!boxes -d vim-shell<CR>
"vmap <leader>x8 !boxes -d simple<CR>
"nmap <leader>x8 !!boxes -d simple<CR>
"vmap <leader>x- !boxes -d stone<CR>
"nmap <leader>x- !!boxes -d stone<CR>
"vmap <leader>x= !boxes -d equals<CR>
"nmap <leader>x= !!boxes -d equals<CR>
"vmap <leader>xu  !boxes -r<CR>
"nmap <leader>xu  !!boxes -r<CR>

" Open URL in another buffer (messes up syntax coloring of other buffers...)
" Requires: browser.vim (script)
map <leader>wv :WebBrowser <c-r><c-a><CR>
imap <leader>wv :WebBrowser <c-r><c-a><CR>
" Browse using the browser.vim plugin, starts the command:
map <leader>ww :WebBrowser 

" Browse to URL under the cursor with a given browser
" Requires: various web browsers (external programs)
" w3m
map <leader>w3 :update<CR>:silent !screen -t 'w3m' w3m '<cWORD>'<CR>
imap <leader>w3 <esc>:update<CR>:silent !screen -t 'w3m' w3m '<cWORD>'<CR>a
" elinks
map <leader>we :update<CR>:silent !screen -t 'elinks' elinks '<cWORD>'<CR>
imap <leader>we <esc>:update<CR>:silent !screen -t 'elinks' elinks '<cWORD>'<CR>a
" opera
map <leader>wo :update<CR>:!opera '<cWORD>'<CR>
imap <leader>wo <esc>:update<CR>:!opera '<cWORD>'<CR>a
" Firefox
map <leader>wf :update<CR>:!firefox '<cWORD>'<CR>
imap <leader>wf <esc>:update<CR>:!firefox '<cWORD>'<CR>a

" play a stream (.pls url for example) with mplayer
"map <leader>bm :update<CR>:!screen -t mplay screen_mplay '<cWORD>'<CR>
"imap <leader>bm <esc>:update<CR>:!screen -t mplay screen_mplay '<cWORD>'<CR>a

" Open current HTML file in given browser (Tip#684):
" Requires: various web browsers (external programs)
" w3m (Linux)
map  <leader>ow :!w3m "%"<CR><Enter>
imap <leader>ow <esc>:!w3m "%"<CR><Enter>a
" links (Linux)
map  <leader>oe :!elinks "%"<CR><Enter>
imap <leader>oe <esc>:!elinks "%"<CR><Enter>a
" Opera (Linux+X)
map  <leader>oo :!open -a opera "%"<CR><Enter>
imap <leader>oo <esc>:!open -a opera "%"<CR><Enter>a
" Dillo (Linux+X)
map  <leader>od :!open -a dillo "%"<CR><Enter>
imap <leader>od <esc>:!open -a dillo "%"<CR><Enter>a
" Firefox (Linux+X)
map  <leader>of :!open -a firefox "%"<CR><Enter>
imap <leader>of <esc>:!open -a firefox "%"<CR><Enter>a
" Safari (Mac)
map  <leader>os :!open -a /Applications/Safari.app "%"<CR><Enter>
imap <leader>os <esc>:!open -a /Applications/Safari.app "%"<CR><Enter>a


" ---- Keyboard Remappings ---------------------------------------------

" HappyHacking Kybd specific mapping: Alt-Return deletes word before cursor,
" Fn-Return (embedded 'Enter' key) deletes word after cursor.
" In kmap file, F19 is mapped to 'Alt-Return' & F20 is mapped to 'Enter'.
set <F19>=[33~
set <F20>=[34~
imap <F19> <c-o>db
map <F19> db
imap <F20> <c-o>de
map <F20> de

" The following key-mapping that make use of the - = \ ` keys relate
" to the Happy Hacking keyboard, where I've re-mapped the embedded
" cursor keys (Left Down Up Right) into these upper right-most four
" keys. The F keys are used here to send console terminal keycodes,
" allowing this to work in terminal versions of Vim (Tip 1272).

" forward/backward by word mapped to Alt-` , Alt--
set <F28>=`
map <F28> <a-`>
map! <F28> <a-`>
map <a-`> el
imap <a-`> el
set <F25>=-
map <F25> <a-->
map! <F25> <a-->
map <a--> b
imap <a--> b

" the same for an Apple keyboard, with Right & Left AltGr mapped to
" Meta_dollar & Meta_asciicircum respectively
set <F30>=$
map <F30> <m-$>
map! <F30> <m-$>
map <m-$> el
imap <m-$> el
set <F31>=^
map <F31> <m-^>
map! <F31> <m-^>
map <m-^> b
imap <m-^> b

" down/up by screen-line mapped to Alt-= , Alt-\
set <F26>==
map <F26> <a-=>
map! <F26> <a-=>
map <a-=> gj
imap <a-=> gj
set <F27>=\
map <F27> <a-\>
map! <F27> <a-\>
map <a-\> gk
imap <a-\> gk

" the same for an Apple keyboard, with Up & Down AltGr mapped to
" Meta_plus & Meta_minus respectively
set <F32>=+
map <F32> <m-+>
map! <F32> <m-+>
map <m-+> gj
imap <m-+> gj
set <F33>=-
map <F33> <m-->
map! <F33> <m-->
map <m--> gk
imap <m--> gk

" for an Apple keyboard, with Right & Left Alt mapped to
" Meta_parenright & Meta_parenleft respectively
set <F34>=)
map <F34> <m-)>
map! <F34> <m-)>
map <m-)> )
imap <m-)> )
set <F35>=(
map <F35> <m-(>
map! <F35> <m-(>
map <m-(> (
imap <m-(> (

" decrease / increase window height: Alt-j / Alt-k
set <F22>=j
map <F22> <a-j>
map! <F22> <a-j>
map <a-j> <c-w>-
imap <a-j> <esc><c-w>-a
set <F23>=k
map <F23> <a-k>
map! <F23> <a-k>
map <a-k> <c-w>+
imap <a-k> <esc><c-w>+a
" decrease / increase window width: Alt-h / Alt-l
set <F21>=h
map <F21> <a-h>
map! <F21> <a-h>
map <a-h> <c-w><
imap <a-h> <esc><c-w><a
set <F24>=l
map <F24> <a-l>
map! <F24> <a-l>
map <a-l> <c-w>>
imap <a-l> <esc><c-w>>a

" Used with a keymap setting F15=Ctrl-Space, F16=Ctrl-BackSpace, F17=Alt-Space
" and F18=Alt-BackSpace; these key combinations will scroll forward one page,
" backward one page, forward one line, backward one line.

set <F15>=[28~
set <F16>=[29~
set <F17>=[31~
set <F18>=[32~
map <F15>   
imap <F15>  <esc>a
map <F16>   
imap <F16>  <esc>a
map <F17>   
imap <F17>  
map <F18>   
imap <F18>  

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"" go to next buffer / previous buffer (F11 & F12 mapped to Fn-Tab & Fn-Esc "
"" in Happy Hacking Keyboard via kmap file)                                 "
" set <F11>=[23~                                                           "
" set <F12>=[24~                                                           "
" map <F11> :bnext!<CR>                                                      "
" imap <F11> <esc>:bnext!<CR>a                                               "
" map <F12> :bprevious!<CR>                                                  "
" imap <F12> <esc>:bprevious!<CR>a                                           "
"                                                                            "
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""


" ---- miscellanea to revisit ------------------------------------------

" Tabs -- not using them as much now...need to reevaluate these mappings
set showtabline=1
" go to previous tab / next tab
map <leader>[ :tabprevious<CR>
imap <leader>[ <C-O>:tabprevious<CR>
map <leader>] :tabnext<CR>
imap <leader>] <C-O>:tabnext<CR>
" open a new tab page with an empty window & then prompt for a file to open
map <leader>tt :tabe 
imap <leader>tt <C-O>:tabe 
" go to next tab / previous tab (F11 & F12 mapped to Fn-Tab & Fn-Esc
" in Happy Hacking Keyboard via kmap file)
set <F11>=[23~
set <F12>=[24~
map <F11> :tabnext<CR>
imap <F11> <esc>:tabnext<CR>a
map <F12> :tabprevious<CR>
imap <F12> <esc>:tabprevious<CR>a
" close tab & delete buffer without closing window
nmap <leader>t- :bn<CR>:bw#<CR>:tabclose<CR>

" Toggle status line on & off (do I want this? If so, figure out a better way)
"map <leader><space> :set laststatus=0<cr>
"imap <leader><space> <esc>:set laststatus=0<cr>
"map <leader><BackSpace> :set laststatus=2<cr>
"imap <leader><BackSpace> <esc>:set laststatus=2<cr>
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" map <leader><space> :set laststatus=0<cr>:CMiniBufExplorer<cr><cr>        "
" imap <leader><space> <esc>:set laststatus=0<cr>:CMiniBufExplorer<cr>a     "
" map <leader><BackSpace> :set laststatus=2<cr>:TMiniBufExplorer<cr><cr>    "
" imap <leader><BackSpace> <esc>:set laststatus=2<cr>:TMiniBufExplorer<cr>a "
"                                                                           "
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

" reStructuredText tools (using Pandoc's extended Markdown now, just
" keeping this around to maybe apply some of this to markdown syntax.
" ...
" mark visually selected text as a link
"vnoremap <leader>ru y gv <Esc>`>a<CR><Esc>`<i<CR><Esc>I`<esc>g_a`_<esc>kJJG()i<esc>p0i.. _<c-o>$:
"vnoremap <leader>ru y gv<Esc>`>a<CR><Esc>`<i<CR><Esc>I<esc>g_a_<esc>kJJG()i<esc>p0i.. _<c-o>$: 
"inoremap <leader>ru <esc>bvey gv <Esc>`>a<CR><Esc>`<i<CR><Esc>I<esc>g_a_<esc>kJJG()i<esc>p0i.. _<c-o>$: 
" map <leader>r- yypv$r-o<esc>o
" map! <leader>r- <esc>yypv$r-o<esc>o
" map <leader>r= yypv$r=o<esc>o
" map! <leader>r= <esc>yypv$r=o<esc>o
" map <leader>r' yypv$r'o<esc>o
" map! <leader>r' <esc>yypv$r'o<esc>o
" map <leader>r` yypv$r`o<esc>o
" map! <leader>r` <esc>yypv$r`o<esc>o
" map <leader>r. yypv$r.o<esc>o
" map! <leader>r. <esc>yypv$r.o<esc>o
" map <leader>r~ yypv$r~o<esc>o
" map! <leader>r~ <esc>yypv$r~o<esc>o
" map <leader>r+ yypv$r+o<esc>o
" map! <leader>r+ <esc>yypv$r+o<esc>o

" ConTeX source files (need to dive into ConTeX & figure this stuff out...)
" save file, generate PDF, delete temporary files, preview pdf in TeXniscope
"
map  <leader>df <esc>k:w<CR>:silent !texexec --pdf %:p<CR>:silent !texutil --purge %<<CR>:silent !open -a /Applications/TeXniscope.app %<".pdf"<CR>kk<c-l>
map! <leader>df <esc>k:w<CR>:silent !texexec --pdf %:p<CR>:silent !texutil --purge %<<CR>:silent !open -a /Applications/TeXniscope.app %<".pdf"<CR>kk<c-l>a

map <leader>dgv <esc>k:w<CR>:silent !texexec --pdf %:p<CR>:silent !texutil --purge %<<CR>:silent !gv %<".pdf"<CR>kk<c-l>
map! <leader>dgv <esc>k:w<CR>:silent !texexec --pdf %:p<CR>:silent !texutil --purge %<<CR>:silent !gv %<".pdf"<CR>kk<c-l>a

map <leader>dvi <esc>k:w<CR>:silent !texexec %:p<CR>:silent !xdvi %<".dvi"<CR>kk<c-l>
map! <leader>dvi <esc>k:w<CR>:silent !texexec %:p<CR>:silent !xdvi %<".dvi"<CR>kk<c-l>a
" map <leader>dvt <esc>k:w<CR>:silent !texexec %:p >/dev/null<CR>:silent !xdvi %<".dvi"<CR>kk<c-l>


" ---- autocommands ----------------------------------------------------

" read Ms-Word documents, requires 'antiword' (tip#305)
autocmd BufReadPre *.doc set ro
autocmd BufReadPre *.doc set hlsearch!
autocmd BufReadPost *.doc %!antiword "%"

" read RTF documents, requires 'UnRTF'
autocmd BufReadPre *.rtf set ro
autocmd BufReadPre *.rtf set hlsearch!
autocmd BufReadPost *.rtf %!unrtf --text "%"

" when we reload, tell vim to restore the cursor to the saved position
" http://vim.wikia.com/wiki/VimTip80
augroup JumpCursorOnEdit
 au!
 autocmd BufReadPost *
 \ if expand("<afile>:p:h") !=? $TEMP |
 \ if line("'\"") > 1 && line("'\"") <= line("$") |
 \ let JumpCursorOnEdit_foo = line("'\"") |
 \ let b:doopenfold = 1 |
 \ if (foldlevel(JumpCursorOnEdit_foo) > foldlevel(JumpCursorOnEdit_foo - 1)) |
 \ let JumpCursorOnEdit_foo = JumpCursorOnEdit_foo - 1 |
 \ let b:doopenfold = 2 |
 \ endif |
 \ exe JumpCursorOnEdit_foo |
 \ endif |
 \ endif
 " Need to postpone using "zv" until after reading the modelines.
 autocmd BufWinEnter *
 \ if exists("b:doopenfold") |
 \ exe "normal zv" |
 \ if(b:doopenfold > 1) |
 \ exe "+".1 |
 \ endif |
 \ unlet b:doopenfold |
 \ endif
augroup END

" remember folds after quitting
autocmd BufWinLeave *.* mkview
autocmd BufWinEnter *.* silent loadview

